### ISSUE TITLE
Welche Controller / API Funktionen sind nötig?

### ISSUE THREAD

**Issue by jhandke** [hhu-propra2/abschlussprojekt-trappin-in-auas#32]

**Comment by LanPodder** [comment]
aktuell ist API auf einer niedrigen priorität. wir versuchen aktuell logik in normalen controllern zu implementieren. diese logik soll dann 1 zu 1 in API form übertragen werden.

d.h. alles was wir für api brauchen ist alles was wir normal brauchen.
in der hinsicht grob:

Bewerbungcontroller: get für bewerbungsformular initialisieren und entsprechender post
Verteilercontroller: get für alle bewerbungen anzeigen. get für spezifische bewerber in detailansicht. post für das verteilen an ansprechpartner.
Controller für ansprechpartner: get um zugewiesene bewerber einzusehen

**Comment by jhandke** [comment]
Ok.
Außerdem brauchen wir für den Verteiler noch jew. einen Controller zum Hinzufügen und Löschen von Modulen sowie zum Zuordnen von Dozenten/Ansprechpartnern zu Modulen
