### ISSUE TITLE
Dritte Rolle und entsprechende user

### ISSUE THREAD

**Issue by LanPodder** [hhu-propra2/abschlussprojekt-trappin-in-auas#41]
Wir brauchen eine unterrolle zu orga.
```
            Orga
        /          \
Verteiler          Dozent
```

Mit entsprechenden Accounts. Hintergrund: nicht jeder Dozent soll die Bewerbungen verteilen können.

Geht das über Keycloak oder müssen wir da selber was hinbekommen?

**Comment by jhandke** [comment]
Wir haben mit Jens darüber gesprochen. Wir bekommen eine Rolle ÜBER Orga. Jeder Dozent hat die Rolle "ROLE_orga" und damit auch alles "darunter".

**Comment by jhandke** [comment]
#75 Wir haben jetzt die Rollen setup und verwaltung. Ich habe gesehen, dass @LanPodder schon einen Config-Enum erstellt hat, sollen wir das vielleicht besser mit einer .properties Datei machen und mit Hilfe von @Value überall injecten lassen, wo es benötigt wird? Dann muss nichts am Code verändert werden, wenn sich Keycloak ändert.
So wurde es auch letzte Woche mit Jens abgesprochen.

**Comment by AcnoZed** [comment]
Klingt gut !

**Comment by LanPodder** [comment]
find ich gut. kein code ändern zu müssen is nice. wenn jens das sogar vorgeschlagen hat seh ich kein problem damit.

**Comment by jhandke** [comment]
Die Rollenzuteilung wurde mit #78 in der Klasse KeycloakRoles gelöst. Leider sind injectete Values nicht zur Compilezeit konstant und konnten deshalb nicht in die Secured Annotationen gesteckt werden.
